---
title: "193DS_file"
author: Mariko Bronson
date: 06-08-2025
format:
  html:
    execute:
      message: false 
      warning: false 
---

https://github.com/MarikoBron/ENVS-193DS_spring-2025_final.git

```{r data-and-packages}

#installing packages
library(tidyverse)
library(here)
library(janitor)
library(flextable)
library(readxl)
library(ggplot2)
library(colorspace)
library(dplyr) 

#create object screentime from my data
screentime <- read_xlsx(
  here("data", "193DS_screentime_updated.xlsx"),
  sheet = "Sheet1")

```

# Problem 1: Research Writing

## a. Transparent statistical methods

In part 1, they used a Pearson's correlation to find how the variables are related to each other. In part 2, they used an ANOVA to find whether the means of multiple groups.

## b. More information needed

In part 2, along with the ANOVA, he should include the effect size and the Turkey HSD. The ANOVA tells you whether there is a difference in the means, and the effect size tells you how large of an effect sources have on the difference. This is important because it helps you find out what might be causing these differences. The ANOVA tells you whether differences are present, and the Turkey HSD will tell you which groups are different and by how much. 

## c. Suggestions for rewriting

Our research suggests that there is a positive correlation between annual total nitrogen load (kg/year) and distance from headwater (km) in the San Joaquin Delta River(Pearson's correlation, r = correlation coefficient, p = 0.03, $\\alpha$ = 0.05) with a large($\\eta^2$ = effect size) effect of distance. Sources(urban land, atmospheric depostion, fertilizer, wastewater treatment, and grasslands) differed in average nitrogen load (one-way ANOVA, F(4, df) = test statistic, p = 0.02, $\\alpha$ = 0.05). We found that fertilizer had a higher nitrogen load than atmospheric deposition (Tukey HSD, p = significance, 95% confidence interval: [lower CI, upper CI] kg/year), and atmospheric deposition had a higher nitrogen load than wastewater treatment (Tukey HSD, p = significance, 95% confidence interval: [lower CI, upper CI] kg/year).
